- name: Deploy to VPS via SSH + rsync
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_SSH_KEY }}
    script: |
      # rsync があるか確認
      rsync --version || sudo apt install -y rsync

      # ディレクトリ作成
      mkdir -p /home/ubuntu/staging-app

      # ファイル同期
      rsync -avz --exclude node_modules --exclude .git ./ /home/ubuntu/staging-app

      # Docker Compose 再起動
      cd /home/ubuntu/staging-app
      docker compose -f docker-compose.staging.yml pull
      docker compose -f docker-compose.staging.yml up -d --build
