- name: Test SSH connection
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_SSH_KEY }}
    script: |
      echo "SSH 接続成功"
      whoami
      pwd
